apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 5m
            memory: 256m
        ports:
        - containerPort: 8080
        env:
          # database service name, of mysql, for phpmyadmin
          - name: PMA_HOSTS 
            value: mysql-service
          # database port, of mysql, for phpmyadmin
          - name: PMA_PORT
            value: "3306"
          # mysql password for root
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_root_password
          # mysql username - optional
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_root_username
          # mysql users password - optional
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_root_password
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30303
